Repository lifeomic/chroma-react, pull requests merged in 2020-10, with the labels that each got.

#15 fix: Yarn install instructions, name of package being installed.
  README.md
Labels: documentation

#16 DOCS: Deploy storybook to gh pages
  .github/workflows/storybook.yml
  package.json
  yarn.lock
Labels: documentation, enhancement

#18 DOCS + FIX: Update documentation and fix typos
  README.md
  package.json
  stories/_guides/componentTheming.md
  stories/_guides/gettingStarted.stories.tsx
  stories/_guides/install.md
  stories/_guides/overview.md
  stories/_guides/theming.md
  stories/_guides2/intro.md
  stories/_guides2/intro.stories.tsx
  stories/_recipes/formik.md
  stories/_recipes/intro.stories.tsx
  stories/_recipes/react-hook-form.md
  stories/_recipes/redux-form.md
  stories/components/Alert/default.md
  stories/components/Avatar/badges.md
  stories/components/Avatar/default.md
  stories/components/Box/default.md
  stories/components/Breadcrumbs/default.md
  stories/components/Button/default.md
  stories/components/ButtonFilePicker/default.md
  stories/components/ButtonFloat/default.md
  stories/components/ButtonLink/default.md
  stories/components/PageLayout/sidebar.md
  stories/components/PageLayout/tabs.md
  stories/styles/boxShadows/default.md
  stories/styles/theme/default.md
Labels: documentation

#19 CHROM add flex-start and flex-end
  src/components/Box/Box.test.tsx
  src/components/Box/Box.tsx
Labels: enhancement, hacktoberfest-accepted

#20 Chroma Version - v0.1.4
  package.json
Labels: dependencies, hacktoberfest-accepted

#21 Bugfix - ComboBox multi selection cuts off
  src/components/Select/Select.tsx
  stories/components/ComboBox/ComboBox.stories.tsx
Labels: bug, hacktoberfest-accepted

#22 CHROMA - v0.1.5
  package.json
Labels: dependencies, hacktoberfest-accepted

#31 FIX: Allow left align override on last column header and cell
  src/components/TableModule/TableHeaderCell.tsx
  src/components/TableModule/TableModuleCell.test.tsx
  src/components/TableModule/TableModuleCell.tsx
Labels: bug

#33 TESTS: Improve Table Module test cases
  src/components/TableModule/TableHeaderCell.test.tsx
  src/components/TableModule/TableModuleCell.test.tsx
Labels: enhancement
