Repository lifeomic/chroma-react, pull requests merged in 2021-07, with the labels that each got.

#169 fix: Import CSS for PhoneNumberFormatField + docs
  jest.config.js
  src/components/NumberFormat/PhoneNumberFormatField.tsx
  stories/components/NumberFormat/PhoneNumberFormatField.stories.tsx
  stories/components/NumberFormat/phoneNumberFormat.md
  test/emptyMock.js
Labels: bug, documentation

#170 fix: Add "align" to Text component
  src/components/Text/Text.test.tsx
  src/components/Text/Text.tsx
  stories/components/Text/Text.stories.tsx
  stories/components/Text/default.md
Labels: enhancement

#171 docs: use chromicons over internal icons
  stories/components/Alert/Alert.stories.tsx
  stories/components/Button/Button.stories.tsx
  stories/components/ButtonFloat/ButtonFloat.stories.tsx
  stories/components/ButtonLink/ButtonLink.stories.tsx
  stories/components/ButtonUnstyled/ButtonUnstyled.stories.tsx
  stories/components/Divider/Divider.stories.tsx
  stories/components/IconButton/IconButton.stories.tsx
  stories/components/IconButtonFloat/IconButtonFloat.stories.tsx
  stories/components/IconButtonLink/IconButtonLink.stories.tsx
  stories/components/IconTile/IconTile.stories.tsx
  stories/components/Icons/Icons.stories.tsx
  stories/components/LayoutManager/LayoutManager.stories.tsx
  stories/components/Menu/Menu.stories.tsx
  stories/components/Select/Select.stories.tsx
  stories/components/TableModule/TableModule.stories.tsx
  stories/components/TextArea/TextArea.stories.tsx
  stories/components/TextField/TextField.stories.tsx
Labels: documentation

#173 fix: checkbox disabled state styles
  src/components/Checkbox/Checkbox.tsx
Labels: bug
