Repository lifeomic/chroma-react, pull requests merged in 2021-06, with the labels that each got.

#138 Combo box disabled options
  src/components/Select/ComboBox.test.tsx
  src/components/Select/ComboBox.tsx
  stories/components/ComboBox/ComboBox.stories.tsx
Labels: bug

#159 FEAT: Add chromicons and use them over internal icons
  package.json
  src/components/Chip/Chip.tsx
  src/components/ExpansionPanel/ExpansionPanel.tsx
  src/components/Modal/Modal.tsx
  src/components/PrimaryNavigation/PrimaryNavigationExpansionItem.tsx
  src/components/Select/ComboBox.tsx
  src/components/Select/Select.tsx
  src/components/SlideOver/Header.tsx
  src/components/Snackbar/Snackbar.tsx
  src/components/TableModule/TableHeaderCell.tsx
  src/components/TableModule/TableModuleRow.tsx
  yarn.lock
Labels: enhancement

#163 DOCS: Add deprecation notice to icon docs
  stories/components/Icons/adaptiveIcons.md
  stories/components/Icons/filledIcons.md
  stories/components/Icons/linedCustomIcons.md
  stories/components/Icons/linedIcons.md
  stories/components/Icons/overview.md
Labels: documentation
