Repository lifeomic/chroma-react, pull requests merged in 2021-08, with the labels that each got.

#180 fix: Use latest ^1.0.0 of chromicons
  package.json
  yarn.lock
Labels: dependencies

#179 feat: add start and end adornments to TextField
  src/components/TextField/TextField.test.tsx
  src/components/TextField/TextField.tsx
  stories/components/TextField/TextField.stories.tsx
  stories/components/TextField/default.md
Labels: enhancement

#182 docs: Add `aria-hidden` to adornment icons
  stories/components/TextField/TextField.stories.tsx
  stories/components/TextField/default.md
Labels: documentation, a11y
