Repository lifeomic/chroma-react, pull requests merged in 2021-03, with the labels that each got.

#69 Create ButtonUnstyled
  src/components/ButtonUnstyled/ButtonUnstyled.test.tsx
  src/components/ButtonUnstyled/ButtonUnstyled.tsx
  src/components/ButtonUnstyled/index.ts
  src/styles/overrides/ChromaOverrides.ts
  stories/components/ButtonUnstyled/ButtonUnstyled.stories.tsx
  stories/components/ButtonUnstyled/default.md
Labels: a11y

#70 v0.2.5
  package.json
Labels: dependencies

#74 ButtonUnstyled - add color inherit
  src/components/ButtonUnstyled/ButtonUnstyled.tsx
Labels: bug

#75 v0.2.7
  package.json
Labels: dependencies

#79 A11y Button
  src/colors/blue.ts
  src/components/Button/Button.tsx
  src/styles/__snapshots__/createTheme.test.ts.snap
Labels: a11y

#80 A11y ButtonFilePicker
  src/components/ButtonFilePicker/ButtonFilePicker.tsx
Labels: a11y

#81 A11y ButtonLink
  src/components/ButtonLink/ButtonLink.tsx
Labels: a11y

#82 A11y Chip
  src/components/Chip/Chip.tsx
Labels: a11y

#83 A11y Pill
  src/components/Pill/Pill.tsx
Labels: a11y

#84 A11y IconTile
  src/components/IconTile/IconTileContent.tsx
Labels: a11y

#85 A11y SmallTile
  src/components/SmallTile/SmallTileFooter.tsx
Labels: a11y

#86 a11y Checkbox
  src/components/Checkbox/Checkbox.tsx
  stories/components/Checkbox/Checkbox.stories.tsx
Labels: a11y

#87 a11y Radio group minimal color contrast and story updates
  src/components/Radio/RadioGroupMinimal.tsx
  stories/components/Radio/Radio.stories.tsx
Labels: a11y, bug

#88 a11y Text color palette
  src/colors/text.ts
  src/styles/__snapshots__/createTheme.test.ts.snap
Labels: a11y

#89 a11y Inverse help messages
  src/components/_private/forms/FormHelpMessage.tsx
Labels: a11y

#90 Update secondary (green) and error (red) palettes
  src/colors/green.ts
  src/colors/red.ts
  src/styles/__snapshots__/createTheme.test.ts.snap
Labels: enhancement

#91 a11y Form error message contrast
  src/components/_private/forms/FormErrorMessage.tsx
Labels: a11y

#92 A11y - Stories updates
  stories/components/ComboBox/ComboBox.stories.tsx
  stories/components/Divider/Divider.stories.tsx
  stories/components/FormBox/FormBox.stories.tsx
  stories/components/Link/Link.stories.tsx
  stories/components/SearchField/SearchField.stories.tsx
  stories/components/Select/Select.stories.tsx
  stories/components/TableModule/TableModule.stories.tsx
  stories/components/TextArea/TextArea.stories.tsx
  stories/components/TextField/TextField.stories.tsx
  stories/components/Toggle/Toggle.stories.tsx
Labels: a11y

#94 A11y - Last pass color contrast
  src/assets/PageLayoutDefaultHero.svg
  src/components/IconButton/IconButton.tsx
  src/components/IconButtonLink/IconButtonLink.tsx
  src/components/Stepper/Step.tsx
Labels: a11y

#95 a11y TextField contrast
  src/components/TextField/TextField.tsx
Labels: a11y

#98 a11y TextArea contrast
  src/components/TextArea/TextArea.tsx
Labels: a11y

#99 a11y SearchField contrast
  src/components/SearchField/SearchField.tsx
  stories/components/SearchField/SearchField.stories.tsx
Labels: a11y

#101 Checkbox and Radio inverse background
  src/components/Checkbox/Checkbox.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/RadioGroupMinimal.tsx
Labels: a11y

#102 Add Radio Group Minimal to FormBox demo
  stories/components/FormBox/FormBox.stories.tsx
Labels: enhancement

#104 Feature/color contrast
  src/assets/PageLayoutDefaultHero.svg
  src/colors/blue.ts
  src/colors/green.ts
  src/colors/red.ts
  src/colors/text.ts
  src/components/Button/Button.tsx
  src/components/ButtonFilePicker/ButtonFilePicker.tsx
  src/components/ButtonLink/ButtonLink.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Chip/Chip.tsx
  src/components/IconButton/IconButton.tsx
  src/components/IconButtonLink/IconButtonLink.tsx
  src/components/IconTile/IconTileContent.tsx
  src/components/Pill/Pill.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/RadioGroupMinimal.tsx
  src/components/SearchField/SearchField.tsx
  src/components/Select/GroupHeading.tsx
  src/components/Select/Select.tsx
  src/components/SmallTile/SmallTileFooter.tsx
  src/components/Stepper/Step.tsx
  src/components/TextArea/TextArea.tsx
  src/components/TextField/TextField.tsx
  src/components/Toggle/Toggle.tsx
  src/components/_private/forms/FormErrorMessage.tsx
  src/components/_private/forms/FormHelpMessage.tsx
  src/styles/__snapshots__/createTheme.test.ts.snap
  stories/components/Checkbox/Checkbox.stories.tsx
  stories/components/ComboBox/ComboBox.stories.tsx
  stories/components/Divider/Divider.stories.tsx
  stories/components/FormBox/FormBox.stories.tsx
  stories/components/Link/Link.stories.tsx
  stories/components/Radio/Radio.stories.tsx
  stories/components/SearchField/SearchField.stories.tsx
  stories/components/Select/Select.stories.tsx
  stories/components/TableModule/TableModule.stories.tsx
  stories/components/TextArea/TextArea.stories.tsx
  stories/components/TextField/TextField.stories.tsx
  stories/components/Toggle/Toggle.stories.tsx
Labels: a11y

#105 fix: ButtonFilePicker cursor dead area
  src/components/ButtonFilePicker/ButtonFilePicker.tsx
Labels: bug

#109 Change green on DotLoader
  src/components/DotLoader/DotLoader.tsx
Labels: enhancement

#108 Soften gradient of highlight pill
  src/components/Pill/Pill.tsx
Labels: enhancement

#107 Align first and last column table headers
  src/components/TableModule/TableHeaderCell.tsx
Labels: bug
